import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home() {

  const [facts, setFacts] = useState('')
  const [isClicked, setIsClicked] = useState(false)

  const handleClick = () => {
    axios.get('https://api.aakhilv.me/fun/facts')
    .then(res => {
      setFacts(res.data[0])
      setIsClicked(true)
    })
    .catch(err => {
      console.log(err)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>FunFacts!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">FunFacts!</a>
        </h1>

        <p className={styles.description}>
          {
            !isClicked
            ?
           'Get started by clicking the button'
           :
           `"${facts}"`
          }
        </p>
        <br/>
        <button onClick={() => {
          handleClick()
        }}>
          {
            !isClicked
            ?
            'Lets Go'
            :
            'More ...'
          }
        </button>
      </main>
    </div>
  )
}
